### ISSUE TITLE
Last update interval isn't calculated

### ISSUE THREAD

**Issue by Jaceken** [ably/asset-tracking-android-customer-app-demo#24] opened 2022-08-04 15:20 UTC
:red_circle:  **Issue**
The _Last update interval_ is often calculated as 0 while the _Average update interval_ changes constantly 

🏞️ **Environment**
Tested using app v.
Android Client app v1.0(12)
:phone: Google Pixel 5 Android 12

🦶 **Steps to reproduce**

1. open the app
1. enter Trackable ID
1. pull up the bottom sheet

Reproducibility: 7/10.

![Screenshot!UNITO-UNDERSCORE!20220804-091118](https://user-images.githubusercontent.com/17332689/182884434-1d1833e2-0b13-453a-8e20-75b842c8a73c.png)

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2509) by [Unito](https://www.unito.io)

**Comment by davyskiba** [comment] 2022-09-02 09:26
Closing as I am not able to reproduce the issues

**Closed by davyskiba** 2022-09-02 09:26 UTC
